In [1]:
import pandas as pd
from datasets import load_dataset, Dataset

/opt/conda/envs/afrimmd/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
test_data = pd.read_csv("finetune/test_predictions.csv", index_col=0)
allowed_languages = ["kik_Latn", "ibo_Latn", "yor_Latn", "hau_Latn", "amh_Ethi", "afr_Latn", "kin_Latn"]
test_data = test_data[test_data["language"].isin(allowed_languages)]
test_data.head()

,predictions,references,language,candidates
id,,,,
1,"[256025, 71112, 1022, 8423, 248272, 62, 14405,...",Mũndũ ũrarĩithia gĩcagi nĩ ahurũkaga thĩ kũger...,kik_Latn,Mũndũ ũrarũ na skithagi kĩa aurũkaga rũ yagere...
3,"[256025, 61493, 80, 35, 248116, 75223, 188, 35...",Imbwa y'umukara yambaye ishati y'ibara ry'umuh...,kin_Latn,Imbwa y'umukara yambaye ishati y'umuh ry'umuho...
5,"[256047, 48903, 201037, 62, 248105, 1825, 5, 8...",Nwa agbọghọ na-aga ịnwa ịkụ bọọlụ tennis .,ibo_Latn,Otu agbọghọ na-eto nwụ ịkụ bọọlụ tennis .
6,"[256051, 3963, 139108, 399, 3911, 3911, 133946...",Ọkùnrin kan tó ń ṣeré yìnyín sọ̀kalẹ̀ lórí òkè .,yor_Latn,Ọkùnrin kan ń ń rìneré lórínyín lórí̀kalẹ̀ lór...
8,"[256073, 3963, 139108, 11837, 11837, 94249, 39...",Ọkùnrin kan àti obìnrin kan ń wo ère aláwọ̀ pu...,yor_Latn,Ọkùnrin àti àti obìnrin kan ń wo àwòránre pupa...

In [3]:
raw_data = load_dataset("AfriMM/AFRICaption")["train"]

In [4]:
raw_data = raw_data.remove_columns(["id", "image_id"])
# Get all language columns except 'id', 'image_id', and 'eng'
lang_columns = [col for col in raw_data.column_names if col !='eng']

# Flatten the dataset: for each row, create a new row for each language
flattened_rows = []
for row in raw_data:
    for lang in lang_columns:
        flattened_rows.append({
            'eng': row['eng'],
            'local_caption': row[lang]
        })

combined_df = pd.DataFrame(flattened_rows)

In [5]:
merged_data = pd.merge(
    test_data, 
    combined_df,
    left_on='references',
    right_on='local_caption',
    how='left'
)

In [6]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3130 entries, 0 to 3129
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   predictions    3130 non-null   object
 1   references     3130 non-null   object
 2   language       3130 non-null   object
 3   candidates     3130 non-null   object
 4   eng            3130 non-null   object
 5   local_caption  3130 non-null   object
dtypes: object(6)
memory usage: 146.8+ KB

In [7]:
merged_data.drop_duplicates(subset=['references'], inplace=True)
merged_data.drop(columns=['predictions','local_caption', "language"], inplace=True)

In [8]:
merged_data

,references,candidates,eng
0,Mũndũ ũrarĩithia gĩcagi nĩ ahurũkaga thĩ kũger...,Mũndũ ũrarũ na skithagi kĩa aurũkaga rũ yagere...,A skier slides along a metal rail .
1,Imbwa y'umukara yambaye ishati y'ibara ry'umuh...,Imbwa y'umukara yambaye ishati y'umuh ry'umuho...,A brown dog in a pink shirt runs through a fie...
2,Nwa agbọghọ na-aga ịnwa ịkụ bọọlụ tennis .,Otu agbọghọ na-eto nwụ ịkụ bọọlụ tennis .,A young girl is about to attempt to hit a tenn...
3,Ọkùnrin kan tó ń ṣeré yìnyín sọ̀kalẹ̀ lórí òkè .,Ọkùnrin kan ń ń rìneré lórínyín lórí̀kalẹ̀ lór...,A man skiing down a snow covered mountain .
4,Ọkùnrin kan àti obìnrin kan ń wo ère aláwọ̀ pu...,Ọkùnrin àti àti obìnrin kan ń wo àwòránre pupa...,A man and a woman looking at a red sculpture .
...,...,...,...
3125,Umugore wari wambaye agapfukamunwa akubita umw...,Umugore w wambaye agapfukamunwa ybita umwana maso,A woman wearing a head covering holding an infant
3126,Twee honde aan leibande wat na mekaar toe span...,Twee honde wat traibande wat mekaar mekaar dra...,Two dogs on leashes straining toward each othe...
3127,Wani mutum yana tafiya a kan ƙasa mai tsawo ku...,Wani mutum yana tafiya da kan tafi mai tsawo k...,A man skateboards down a steep railing next to...
3128,kamwana gaarĩ na nguo cia kwĩhumba iria rĩarĩ ...,kamwana kaniniarĩ na nguo cia gũthhumba iria r...,a young boy wearing a colorful bathing suit sp...
3129,Nwa agbọghọ na-amụmụ ọnụ ọchị n'okpu crouched ...,Otu agbọghọ na-amụmụ ọnụ ọchị na'okpu naouchin...,a young smiling girl in a hat crouched in a field

In [9]:
merged_data = merged_data.rename(columns={"references": "ref", "eng":"src", "candidates": "mt"})

In [10]:
merged_data_dicts = merged_data.to_dict(orient="records")

In [11]:
from comet import download_model, load_from_checkpoint

model_path = download_model("masakhane/africomet-mtl")
model = load_from_checkpoint(model_path)
model_output = model.predict(merged_data_dicts, batch_size=16, gpus=1)
print(model_output)

Fetching 4 files: 100%|██████████| 4/4 [00:07<00:00,  2.00s/it]
Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.5.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/huggingface/hub/models--masakhane--africomet-mtl/snapshots/c00016e2a120e8583b36c602d7be69ba1b45f088/checkpoints/model.ckpt`
Encoder model frozen.
You are using the plain ModelCheckpoint callback. Consider using LitModelCheckpoint which with seamless uploading to Model registry.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA L4') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Predicting DataLoader 0: 100%|██████████| 178/178 [01:04<00:00,  2.75it/s]

Prediction([('scores', [0.26181215047836304, 0.6051399111747742, 0.5661895275115967, 0.45209214091300964, 0.5516659617424011, 0.19104453921318054, 0.6716539263725281, 0.3902663588523865, -0.05242149159312248, -0.06297816336154938, 0.41617104411125183, 0.09705983847379684, 0.4976620078086853, 0.5441562533378601, 0.3860210180282593, 0.14193668961524963, -0.15859876573085785, 0.45026323199272156, -0.07248911261558533, 0.5482356548309326, 0.7474896311759949, 0.7741848826408386, 0.8663567304611206, 0.11609955132007599, 0.7687346935272217, 0.8535468578338623, 0.22224001586437225, 0.8419792652130127, 0.18991288542747498, 0.16725942492485046, 0.12715092301368713, 0.5747005343437195, 0.41789907217025757, 0.5091909170150757, 0.46613258123397827, 0.7121192812919617, -0.09664267301559448, 0.15151390433311462, 0.43159884214401245, 0.5150694847106934, 0.44594842195510864, 0.5440855026245117, 0.38210153579711914, 0.514138400554657, 0.8166230916976929, 0.4045946002006531, -0.049023717641830444, 0.41124504804611206, 0.5105047225952148, -0.16581237316131592, 0.7482286691665649, 0.36423319578170776, 0.5369419455528259, 0.45705825090408325, 0.6336854696273804, -0.1428351253271103, 0.5928324460983276, 0.42581653594970703, 0.6327450275421143, 0.34085601568222046, 0.6503458023071289, 0.6283780932426453, 0.6564321517944336, 0.26545384526252747, 0.08585304021835327, 0.4622192084789276, 0.11909123510122299, 0.07609259337186813, 0.11851376295089722, 0.37790584564208984, 0.4672994613647461, 0.9089242219924927, 0.14850665628910065, 0.1836770474910736, 0.8248037099838257, 0.5404015779495239, 0.41184791922569275, 0.5227504968643188, 0.8470773696899414, 0.822453498840332, 0.8493308424949646, 0.27664846181869507, 0.6605802774429321, 0.5947200059890747, 0.21461723744869232, 0.5036916732788086, 0.7860679626464844, -0.2363797128200531, 0.19614748656749725, 0.31063351035118103, 0.08543922752141953, 0.37250155210494995, 0.5454443693161011, 0.5028009414672852, 0.30832967162132263, 0.6138340830802917, 0.4840533435344696, 0.6718883514404297, 0.8724715113639832, -0.05900092050433159, 0.7439038157463074, 0.16690057516098022, 0.5579882264137268, 0.6034684777259827, 0.44106239080429077, 0.4560546875, 0.2816224694252014, 0.4751225411891937, 0.5152191519737244, 0.7330420017242432, 0.20468354225158691, 0.6315363645553589, 0.7015077471733093, 0.617660403251648, 0.3835300803184509, 0.4815874993801117, 0.008321108296513557, 0.5637959241867065, 0.5364620089530945, 0.5009341239929199, 0.49894005060195923, 0.3851885199546814, 0.36043089628219604, 0.41166600584983826, 0.05058087036013603, 0.42181146144866943, 0.1111573800444603, 0.04161655530333519, 0.13382738828659058, 0.7715634703636169, 0.45325979590415955, 0.47456929087638855, -0.13250760734081268, 0.6723992824554443, 0.14158865809440613, 0.030331751331686974, 0.05883985757827759, 0.5353492498397827, 0.4234102666378021, 0.7098499536514282, 0.3317161202430725, 0.3079337775707245, 0.6799699664115906, 0.20670846104621887, 0.3321880102157593, 0.7062151432037354, 0.29317063093185425, 0.07557950913906097, 0.39168834686279297, 0.7409700155258179, 0.134485125541687, 0.25224223732948303, 0.7709000110626221, 0.43639764189720154, -0.00946833100169897, 0.748534083366394, 0.7959073781967163, 0.24847161769866943, 0.7732223272323608, 0.49398326873779297, 0.7732025980949402, 0.8689205646514893, 0.6715911626815796, 0.4204608201980591, 0.6866865158081055, -0.011986872181296349, -0.012591734528541565, 0.7781909704208374, 0.43099185824394226, 0.1877223700284958, 0.5793346166610718, -0.17676597833633423, 0.7086354494094849, 0.4585878849029541, 0.3043283224105835, 0.6667534112930298, 0.45817071199417114, 0.4021989703178406, 0.6756999492645264, 0.513219952583313, 0.06748873740434647, -0.007227362599223852, 0.2240632176399231, 0.5826293230056763, 0.5843210220336914, 0.3993176817893982, 0.12125241756439209, 0.7437952756881714, 0.4527991712093353, 0.2597540020942688, 0.24535465240478516, 0.6043044924736023, -0.25239554047584534, 0.4720112979412079, 0.620891809463501, 0.8343827128410339, 0.4128391742706299, 0.5498169660568237, 0.7582753896713257, 0.394412636756897, 0.2572857141494751, 0.013813292607665062, 0.8458974361419678, 0.021383851766586304, 0.18667498230934143, 0.8080436587333679, 0.5933208465576172, 0.7127019762992859, 0.456351101398468, 0.1652754843235016, 0.687100350856781, 0.166529580950737, 0.4827033281326294, 0.7590079307556152, 0.41868555545806885, 0.11215591430664062, 0.342244952917099, -0.0002085020241793245, 0.1408911943435669, 0.2720335125923157, 0.5034348368644714, 0.05845283716917038, 0.5741550326347351, 0.7853984236717224, 0.5955262184143066, 0.10464261472225189, 0.35200628638267517, 0.06871995329856873, 0.5391550064086914, 0.8265479803085327, 0.47845014929771423, 0.5217611193656921, 0.4806153476238251, 0.6926689147949219, 0.25447192788124084, 0.3917176127433777, 0.39290913939476013, 0.11648526042699814, 0.039349764585494995, 0.6477502584457397, 0.5285009145736694, 0.19156619906425476, -0.3418818712234497, 0.2428826540708542, 0.33896374702453613, 0.4898168444633484, -0.2622947096824646, 0.5926690697669983, 0.8178713321685791, 0.29851293563842773, 0.6248827576637268, 0.48564624786376953, 0.3979607820510864, 0.38181811571121216, 0.6304646730422974, 0.37151914834976196, -0.052579864859580994, 0.5234724283218384, 0.3248143792152405, 0.43411073088645935, 0.17457818984985352, 0.06754039227962494, 0.6809488534927368, 0.6190497875213623, 0.33439335227012634, 0.11051328480243683, 0.030437227338552475, 0.08682795614004135, 0.6106525659561157, 0.4982367753982544, 0.4945215582847595, 0.7329387664794922, 0.382310688495636, -0.25195491313934326, 0.7455891370773315, 0.8411824703216553, -0.20734743773937225, 0.08245144784450531, 0.5503053665161133, 0.2081800401210785, 0.3517940938472748, 0.8627109527587891, 0.6083766222000122, -0.17034602165222168, 0.7039695978164673, 0.3093379735946655, 0.758743941783905, 0.05253683775663376, 0.656709611415863, 0.4885268211364746, 0.3377174139022827, 0.7906014919281006, 0.807845950126648, 0.27968496084213257, 0.5947230458259583, 0.6106047034263611, 0.10650821030139923, 0.7106128931045532, 0.8265260457992554, 0.8309194445610046, 0.3374738395214081, -0.049718208611011505, 0.5092944502830505, 0.6359493732452393, 0.5012639760971069, 0.14903602004051208, 0.6275229454040527, -0.027601715177297592, 0.49047064781188965, 0.32483142614364624, 0.5216731429100037, 0.5969676971435547, 0.5950021147727966, 0.5754412412643433, 0.5046533346176147, 0.2564021348953247, 0.5891718864440918, 0.14435167610645294, 0.36321815848350525, -0.023914409801363945, 0.5255745649337769, 0.7289187908172607, -0.06273975968360901, 0.5542117953300476, 0.8631992340087891, -0.015401341021060944, 0.162759929895401, 0.6697627305984497, 0.4699920117855072, 0.11777257919311523, 0.3086346387863159, 0.14582180976867676, -0.1853497475385666, 0.8902512788772583, 0.41492801904678345, 0.11386299133300781, 0.04204702377319336, -0.007190400268882513, 0.03561846539378166, 0.33096373081207275, 0.4239717721939087, 0.6341090202331543, 0.4709426760673523, 0.5159423351287842, 0.46849629282951355, 0.4538036286830902, 0.4641294479370117, 0.7875590324401855, 0.3644348978996277, 0.772103488445282, 0.4952811002731323, 0.14342957735061646, 0.35919737815856934, 0.006120610982179642, 0.2525714337825775, 0.3201389014720917, 0.34233447909355164, 0.2126830518245697, 0.4923589825630188, 0.14619538187980652, 0.38296788930892944, 0.08657543361186981, 0.4778141975402832, 0.7257676124572754, 0.35797256231307983, 0.47020524740219116, 0.7389585375785828, 0.7084783315658569, 0.21195173263549805, 0.7639285922050476, -0.1870644986629486, -0.03630734235048294, 0.5406103134155273, 0.760807454586029, 0.08494265377521515, 0.5588269829750061, 0.5347428321838379, -0.13375574350357056, 0.08514879643917084, 0.44209766387939453, 0.2087453305721283, 0.3159269094467163, 0.3752537667751312, 0.15855735540390015, 0.6262533068656921, 0.5628900527954102, 0.8143298029899597, 0.3876396119594574, 0.007979430258274078, 0.47081467509269714, 0.5923473834991455, 0.8631541728973389, 0.5496557950973511, 0.07898654043674469, -0.15320931375026703, 0.02029835246503353, 0.355893075466156, 0.710664689540863, -0.0265454463660717, 0.7512719035148621, 0.47435706853866577, 0.09902909398078918, 0.655005693435669, -0.20441368222236633, 0.13072210550308228, 0.563300609588623, 0.0310257226228714, 0.174262136220932, 0.3674118220806122, 0.4630817174911499, -0.21856151521205902, 0.6987123489379883, 0.2440813034772873, -0.07540582120418549, 0.6543786525726318, 0.7892264127731323, 0.4244764745235443, 0.09942616522312164, -0.24724362790584564, 0.6784700751304626, 0.5751421451568604, -0.014779455959796906, 0.3839169442653656, 0.48030394315719604, 0.0002987571060657501, 0.5062664747238159, 0.21786057949066162, 0.11129876971244812, 0.8980369567871094, 0.20347967743873596, 0.8102938532829285, 0.519916296005249, 0.6374983787536621, 0.4906265139579773, -0.09304779767990112, 0.7805681228637695, -0.23847317695617676, 0.010095683857798576, 0.6549691557884216, 0.3426554203033447, 0.18896439671516418, 0.48826611042022705, -0.19875037670135498, 0.7213106155395508, 0.004236107226461172, 0.26262545585632324, 0.45491695404052734, 0.17201542854309082, 0.4214315414428711, 0.3254276216030121, -0.03814850002527237, -0.3099735677242279, 0.2592286467552185, 0.15814727544784546, 0.1989648938179016, 0.6304137110710144, 0.5590877532958984, 0.6788452863693237, 0.19590680301189423, 0.7713196277618408, 0.4403165578842163, 0.483268678188324, 0.36716994643211365, 0.7091512680053711, -0.08401833474636078, 0.3352179229259491, 0.2399369478225708, 0.3255554139614105, -0.1497565507888794, 0.35942551493644714, 0.05489695072174072, 0.4034061133861542, 0.5589374303817749, 0.8351642489433289, -0.10559538006782532, 0.36136722564697266, 0.6019131541252136, 0.5928037166595459, 0.7684143781661987, 0.7047858238220215, 0.4433138370513916, 0.54778653383255, 0.3730846345424652, 0.8423206210136414, 0.498443067073822, 0.8108758926391602, 0.6933252215385437, 0.7687931060791016, 0.624053418636322, 0.2718944251537323, 0.30889904499053955, 0.2742348909378052, 0.6541847586631775, 0.6422781944274902, 0.5724184513092041, 0.19030146300792694, -0.00971686840057373, 0.789875864982605, -0.05296040698885918, 0.594022274017334, 0.3079211413860321, -0.059499453753232956, 0.6491250991821289, 0.34893926978111267, 0.3644900321960449, 0.7276973128318787, 0.08176365494728088, 0.5440421104431152, 0.34261608123779297, 0.2992395758628845, 0.13416942954063416, 0.2735365629196167, 0.5702979564666748, 0.6338163614273071, 0.3658927381038666, 0.7795447111129761, 0.2522399127483368, 0.6936623454093933, 0.27913472056388855, 0.611056387424469, 0.16691642999649048, -0.01595257967710495, 0.3189257085323334, 0.6006163358688354, -0.04118015244603157, 0.3910733461380005, 0.19618043303489685, 0.622987687587738, 0.7112653255462646, 0.4952797293663025, 0.0985763669013977, 0.777164876461029, 0.28130725026130676, 0.598091721534729, 0.40331578254699707, 0.24370241165161133, 0.32081514596939087, 0.3069673478603363, 0.0075767748057842255, 0.501861035823822, 0.27569180727005005, 0.7417206168174744, 0.1650739312171936, 0.7455908060073853, 0.12642335891723633, 0.4443158805370331, 0.1531667709350586, 0.08927550911903381, 0.6188125014305115, 0.3523883819580078, 0.6556330919265747, 0.5550612211227417, 0.6501426696777344, 0.7692744135856628, 0.6032297015190125, 0.235030859708786, 0.2987994849681854, 0.6715848445892334, 0.4573768973350525, 0.6900043487548828, 0.6048661470413208, 0.16186946630477905, 0.054340384900569916, 0.02669813483953476, 0.47049185633659363, -0.2697868347167969, 0.5237812399864197, 0.32293838262557983, 0.6155874133110046, 0.41961726546287537, 0.2182898372411728, 0.053959157317876816, 0.17425325512886047, 0.3013134002685547, 0.44901013374328613, 0.7334421873092651, 0.5279750227928162, 0.38253188133239746, 0.025578072294592857, 0.33329588174819946, 0.6712075471878052, 0.16335974633693695, 0.6106488704681396, 0.6179605722427368, 0.42007097601890564, 0.31486067175865173, 0.4627549648284912, 0.10751595348119736, 0.5210068225860596, 0.5849511623382568, 0.7074481844902039, -0.015722310170531273, 0.8413776755332947, 0.7827102541923523, 0.11875513195991516, 0.7595282793045044, 0.13748405873775482, -0.1577417552471161, 0.5802851915359497, 0.613677978515625, 0.4336868226528168, 0.1820581555366516, 0.6296910047531128, -0.11094938218593597, 0.1421305239200592, -0.13823202252388, 0.2073274552822113, 0.7529405355453491, 0.38268518447875977, 0.278079628944397, 0.44088274240493774, -0.1701318472623825, 0.2984055280685425, 0.44161200523376465, 0.48698800802230835, 0.686445951461792, 0.1177009865641594, 0.5539295673370361, 0.5614770650863647, 0.6421772241592407, 0.7212437391281128, 0.44460710883140564, 0.3706609606742859, 0.33906134963035583, 0.5934104919433594, 0.5595090389251709, 0.559123158454895, 0.1314806342124939, 0.842923641204834, 0.635455310344696, 0.47800418734550476, 0.6733855605125427, 0.5554312467575073, 0.5145457983016968, 0.6077790260314941, 0.23384562134742737, 0.49107688665390015, 0.1934361457824707, 0.589500904083252, 0.28524094820022583, 0.4515115022659302, 0.7104174494743347, 0.4319378733634949, -0.07970854640007019, -0.007652593310922384, 0.3696005046367645, 0.2797081470489502, 0.5097495913505554, 0.46720775961875916, 0.18265995383262634, 0.8162758350372314, 0.7310213446617126, 0.40802690386772156, 0.12407730519771576, -0.03703756630420685, -0.041744571179151535, 0.5944568514823914, 0.8998645544052124, 0.171965092420578, 0.3750046193599701, 0.007983870804309845, -0.05918796360492706, 0.6077122688293457, 0.20830178260803223, 0.32001614570617676, 0.6157452464103699, 0.6221905946731567, 0.5647680759429932, 0.31833910942077637, 0.15849852561950684, 0.6341025233268738, 0.6315037608146667, 0.034625496715307236, 0.7765447497367859, 0.17046211659908295, 0.38524508476257324, -0.1206774041056633, 0.4642661511898041, 0.04442097991704941, 0.5751665830612183, 0.3677511215209961, 0.3375365734100342, 0.7150343656539917, 0.31790992617607117, 0.5490542650222778, 0.36890536546707153, 0.33709973096847534, 0.13090775907039642, 0.7933218479156494, 0.39137423038482666, 0.03448545187711716, 0.7103736400604248, 0.6671018600463867, 0.8492202758789062, 0.38730692863464355, 0.1878700703382492, -0.1774158477783203, 0.10226300358772278, 0.5110082626342773, 0.8180787563323975, 0.4300869405269623, 0.4464810788631439, 0.4260062575340271, 0.17639011144638062, 0.5564829111099243, 0.43717169761657715, 0.026366304606199265, 0.23454664647579193, 0.04624565690755844, 0.797778844833374, 0.2980818450450897, 0.009146580472588539, 0.5087098479270935, -0.17273467779159546, 0.6251187324523926, 0.2939299941062927, 0.14434164762496948, 0.1427488923072815, 0.4002503752708435, 0.5859295725822449, 0.13934318721294403, 0.6055500507354736, -0.22482435405254364, 0.39217060804367065, 0.3545183539390564, 0.46124887466430664, 0.30037927627563477, 0.5011368989944458, 0.7099510431289673, 0.6168925166130066, 0.01817166432738304, 0.14140838384628296, 0.22583429515361786, 0.061282142996788025, 0.19901880621910095, 0.005973616149276495, 0.17223650217056274, 0.6207423210144043, 0.20122568309307098, 0.8042722940444946, 0.7527292966842651, -0.06957658380270004, 0.5828196406364441, 0.1807062327861786, 0.4141587018966675, 0.049376003444194794, 0.020848121494054794, 0.8871769905090332, 0.8413418531417847, 0.14103883504867554, 0.3537735342979431, 0.12698133289813995, 0.4409213662147522, -0.07163503766059875, 0.5796108245849609, 0.2508549988269806, 0.24621149897575378, -0.2888280153274536, -0.28639253973960876, 0.516838550567627, 0.5660997033119202, 0.2214718759059906, 0.1851644217967987, 0.10438479483127594, -0.13603830337524414, 0.5011403560638428, 0.28048455715179443, 0.2698128819465637, -0.13091734051704407, 0.5013546943664551, 0.22260253131389618, 0.42002642154693604, 0.4555346667766571, 0.37338119745254517, 0.15157002210617065, 0.18591371178627014, 0.00994831696152687, 0.45216259360313416, -0.02680554986000061, 0.014705012552440166, 0.14391055703163147, 0.13493996858596802, 0.08563190698623657, 0.31358104944229126, 0.30798572301864624, 0.47322067618370056, 0.42138513922691345, 0.10075129568576813, 0.6060137748718262, 0.4647550582885742, 0.6624184846878052, -0.11729400604963303, 0.6125255823135376, 0.04251826927065849, 0.41637182235717773, 0.3222486972808838, 0.13666042685508728, -0.1268015205860138, 0.8043426275253296, -0.14065085351467133, 0.6242730617523193, 0.04856167361140251, 0.4780142903327942, 0.5773448348045349, 0.20638017356395721, 0.8681511878967285, 0.8375732898712158, 0.5351545810699463, 0.0625046044588089, 0.4841237962245941, 0.0657639130949974, -0.19644317030906677, -0.11240842193365097, 0.7206987142562866, 0.577180027961731, 0.7763120532035828, 0.33658453822135925, 0.4573535919189453, 0.1315884292125702, 0.7583069801330566, 0.3192084729671478, 0.5920102596282959, 0.1961437165737152, 0.8048560619354248, 0.5200592279434204, 0.6963340640068054, 0.5648333430290222, 0.3280732035636902, 0.15182232856750488, 0.16748276352882385, 0.5466777682304382, 0.40225934982299805, 0.5393268465995789, 0.09496774524450302, 0.3249146342277527, 0.4213939309120178, 0.5667589902877808, -0.1191207766532898, 0.36016082763671875, 0.6849345564842224, 0.6032613515853882, 0.5196554064750671, 0.040519826114177704, 0.3165975511074066, 0.350943386554718, 0.15186981856822968, 0.009382187388837337, 0.6656083464622498, -0.037926025688648224, 0.09318549931049347, 0.07342894375324249, 0.5904533863067627, 0.09247183799743652, 0.589601993560791, 0.11529968678951263, 0.6815602779388428, 0.3165822923183441, 0.16834551095962524, -0.16871780157089233, 0.48903989791870117, 0.19947932660579681, 0.7846001386642456, 0.7798709869384766, 0.44497150182724, 0.854033887386322, 0.5383750200271606, 0.35049182176589966, 0.5553605556488037, -0.1615843027830124, 0.03824704885482788, 0.7620750665664673, -0.020915310829877853, 0.7838666439056396, 0.10062497854232788, 0.6841784715652466, 0.027877703309059143, 0.6633999943733215, 0.6514133810997009, 0.16620104014873505, 0.01607034169137478, 0.2914015054702759, 0.17830419540405273, 0.574934720993042, 0.16019529104232788, 0.3832336664199829, 0.06573069095611572, 0.30796536803245544, 0.8421769142150879, 0.4160146713256836, 0.21729812026023865, -0.23126277327537537, 0.40496334433555603, 0.3621840178966522, 0.023363638669252396, 0.10033401101827621, 0.4620583951473236, 0.23504512012004852, 0.30918464064598083, 0.3894326090812683, 0.8400522470474243, 0.4358791708946228, 0.4012274444103241, -0.07109050452709198, 0.12001796066761017, 0.810152530670166, 0.7424088716506958, 0.641115665435791, 0.07607964426279068, 0.6827794909477234, 0.3301425874233246, 0.6980763673782349, 0.012505324557423592, 0.07234171777963638, 0.8137156367301941, 0.5702806711196899, 0.355964720249176, -0.04669594764709473, 0.4258515238761902, -0.008338111452758312, 0.30681782960891724, 0.4628024101257324, -0.02787499874830246, -0.016003798693418503, 0.33521604537963867, 0.6550755500793457, 0.7303006052970886, 0.469733327627182, 0.16945287585258484, 0.02913801372051239, 0.7406002283096313, 0.42904147505760193, 0.35109150409698486, 0.5867006778717041, 0.4476168155670166, 0.1861642450094223, 0.6205981969833374, 0.2339826077222824, 0.02582702785730362, 0.21957199275493622, 0.7245410680770874, 0.6706408858299255, 0.06089964509010315, 0.44320809841156006, 0.02175867184996605, 0.7163649797439575, 0.015003877691924572, 0.13325060904026031, 0.2281242460012436, 0.08155633509159088, -0.03471305966377258, 0.15436270833015442, 0.24691984057426453, 0.5117155313491821, -0.1482323408126831, 0.22276270389556885, 0.5594596266746521, 0.3844045102596283, 0.15955482423305511, 0.7686871886253357, 0.27056676149368286, 0.5391108989715576, 0.8350716829299927, 0.8141745328903198, 0.1928010880947113, 0.16268014907836914, 0.18663230538368225, 0.07131104171276093, 0.6608360409736633, 0.21244469285011292, 0.21720543503761292, 0.1523904949426651, 0.32011544704437256, 0.6944186687469482, 0.2900741696357727, -0.03084663860499